name: classicbikereview
favicon: null
layout_spectrum: 0.3152573932893574
typography_spectrum: 0.7163799286354333
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.31012859335169196
  lightness: 0.01572330668568611
  saturation: 0.2750519902911037
  rhythmicContrast: 0.8043357380665839
purpose: []
